/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'swarup' at '11/19/18 1:40 PM' with Gradle 3.1
 *
 * @author swarup, @date 11/19/18 1:40 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
